#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
WHITE='\033[0;37m'
NC='\033[0m' #Normal color

FILE=""
USEFILE=true
KEEPTEST=false

while getopts f:ik option
do
	case "$option" in
		f)
			FILE="$OPTARG" ;;
		i)
			USEFILE=false ;;
		k)
			KEEPTEST=true ;;
		\? | h)
			echo -e "\nUsage: ptest -f [FILENAME] [options]"
			echo -e "\t-i\tUse stdin instead of 'in.txt' as input"
			echo -e "\t-k\tKeep the produced 'test.txt' file"
			echo -e "\t-h\tShow usage\n"
	esac
done

if [[ "$FILE" == "" ]]; then
	echo -e "${RED}Error: no file specified"
	exit
fi

EXTENSION="${FILE##*.}"
NAME="${FILE%.*}"

RunJava()
{
	echo -e "${GREEN}Compiling..."
	javac "$FILE"

	echo -e "${GREEN}Running...${WHITE}"
	START_TIME=0

	if [[ "$USEFILE" == true ]]; then
		START_TIME=`echo $(($(gdate +%s%N)/1000000))`
		java "$NAME" < in.txt > test.txt
	else
		START_TIME=`echo $(($(gdate +%s%N)/1000000))`
		java "$NAME" > test.txt
	fi

	END_TIME=`echo $(($(gdate +%s%N)/1000000))`
	ELAPSED_TIME=$(($END_TIME - $START_TIME))

	echo -e "${GREEN}Runtime: ${ELAPSED_TIME} ms${WHITE}"

	cat test.txt

	echo -e "${GREEN}Checking...${WHITE}"
	DIFF=$(diff -u test.txt out.txt)

	if [[ "$DIFF" == "" ]]; then
		echo -e "${GREEN}Success!${WHITE}"
	else
		echo "$DIFF"
	fi

	echo -e "${GREEN}Removing class file...${NC}"
	rm *.class

	if [[ "$KEEPTEST" == false ]]; then
		echo -e "${GREEN}Removing test file...${NC}"
		rm test.txt
	fi

	echo -e "${GREEN}Done"
}

if [[ "$EXTENSION" == "java" ]]; then
	RunJava
else
	echo -e "${NC}Filetype '$EXTENSION' is not supported"
fi
