#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
WHITE='\033[0;37m'
NC='\033[0m'

FILE="$1"
shift
USEFILE=true
IN_FILE="in.txt"
OUT_FILE=""
SIMPLE=false
JUST_RUN=false
ELAPSED_TIME=0
SAVEFILE=""
DIFF_COMMAND="diff"

RUNS=1

# Detect the platform (similar to $OSTYPE)
DATE_COMMAND="date"

if [[ "$OSTYPE" == "darwin"* ]]; then
  DATE_COMMAND="gdate"
fi

PrintHelp()
{
    echo -e "\\nUsage: run {FILENAME} [options]"
    echo -e "\\t-i\\tSpecify the input file to use"
    echo -e "\\t-o\\tSpecify an expected output file to diff stdout with"
    echo -e "\\t-u\\tUse stdin instead of '$IN_FILE' as input"
    echo -e "\\t-s\\tDo a simple compile and execute"
    echo -e "\\t-r\\tSkip compilation and just run the class"
    echo -e "\\t-b\\tSpecify the amount of times to run the program, and output the average runtime"
    echo -e "\\t-e\\tSpecify a file to pipe output to"
    echo -e "\\t-c\\tUse color for diff (must have colordiff installed)"
    echo -e "\\t-h\\tShow usage\\n"
}

if [[ "$FILE" == "" || "$FILE" == "-h" ]]; then
  PrintHelp
  exit 1
fi

while getopts :i:o:b:e:shurc option
do
  case "$option" in
    i)
      IN_FILE="$OPTARG" ;;
    o)
      OUT_FILE="$OPTARG" ;;
    u)
      USEFILE=false ;;
    r)
      JUST_RUN=true ;;
    c)
      DIFF_COMMAND="colordiff" ;;
    s)
      SIMPLE=true ;;
    b)
      RUNS="$OPTARG" ;;
    e)
      SAVEFILE="$OPTARG" ;;
    \? | h | :) 
      PrintHelp
  esac
done

if [[ "$FILE" == "" ]]; then
  echo -e "${RED}Error: no source file specified"
  exit 1
fi

if [[ "$USEFILE" && "$IN_FILE" == "" ]]; then
  echo -e "${RED}Error: no input file specified"
  exit 1
fi

EXTENSION="${FILE##*.}"
NAME="${FILE%.*}"

CompileJava()
{
  if [[ "$JUST_RUN" != true ]]; then
    echo -e "${GREEN}Compiling...${WHITE}"
    javac "$FILE"
  fi
}

RunJava()
{
  echo -e "${GREEN}Running...${WHITE}"

  if [[ "$SIMPLE" == true ]]; then
    java "$NAME"
    exit
  fi

  START_TIME=0
  OUTPUT=""
  if [[ "$USEFILE" == true ]]; then
    START_TIME=$(($($DATE_COMMAND +%s%N)/1000000))
    OUTPUT=$(java "$NAME" < "$IN_FILE")
  else
    START_TIME=$(($($DATE_COMMAND +%s%N)/1000000))
    OUTPUT=$(java "$NAME")
  fi
  echo -e "$OUTPUT"
  END_TIME=$(($($DATE_COMMAND +%s%N)/1000000))
  ELAPSED_TIME=$((END_TIME - START_TIME))

  if [[ "$SAVEFILE" != "" ]]; then
    echo "$OUTPUT" > "$SAVEFILE"
  fi

  if [[ "$OUT_FILE" != "" ]]; then
    echo -e "${GREEN}Checking difference with output file${WHITE}"
    echo "$OUTPUT" | "$DIFF_COMMAND" - "$OUT_FILE"
  fi

  echo -e "${GREEN}Done"
}

RunPython()
{
  if [[ "$SIMPLE" == true ]]; then
    python "$FILE"
    exit
  fi

  START_TIME=0
  if [[ "$USEFILE" == true ]]; then
    START_TIME=$(($($DATE_COMMAND +%s%N)/1000000))
    python "$FILE" < "$IN_FILE"
  else
    START_TIME=$(($($DATE_COMMAND +%s%N)/1000000))
    python "$FILE"
  fi
  END_TIME=$(($($DATE_COMMAND +%s%N)/1000000))

  ELAPSED_TIME=$((END_TIME - START_TIME))

  echo -e "${GREEN}Done${NC}"
}

CompileCpp()
{
  echo -e "${GREEN}Compiling...${WHITE}"
  g++ -std=c++11 "$FILE" -Wall
}

RunCpp()
{
  echo -e "${GREEN}Running...${WHITE}"

  if [[ "$SIMPLE" == true ]]; then
    ./a.out
    exit
  fi

  START_TIME=0
  if [[ "$USEFILE" == true ]]; then
    START_TIME=$(($($DATE_COMMAND +%s%N)/1000000))
    ./a.out < "$IN_FILE"
  else
    START_TIME=$(($($DATE_COMMAND +%s%N)/1000000))
    ./a.out
  fi
  END_TIME=$(($($DATE_COMMAND +%s%N)/1000000))

  ELAPSED_TIME=$((END_TIME - START_TIME))

  echo -e "${GREEN}Done"
}

if [[ "$EXTENSION" == "java" ]]; then
  CompileJava
elif [[ "$EXTENSION" == "cpp" ]]; then
  CompileCpp
elif [[ "$EXTENSION" == "py" ]]; then
  echo -e "${GREEN}Python cannot be compiled, proceeding to run...${NC}"
else
  echo -e "${NC}Filetype '$EXTENSION' is not supported"
  exit 1
fi

SUM=0
TOTAL=0
TIMES_RAN="$RUNS"

while [[ "$RUNS" -gt 0 ]]
do
  if [[ "$EXTENSION" == "java" ]]; then
    RunJava
  elif [[ "$EXTENSION" == "py" ]]; then
    RunPython
  elif [[ "$EXTENSION" == "cpp" ]]; then
    RunCpp
  fi

  SUM=$((SUM + ELAPSED_TIME))
  TOTAL=$((TOTAL + 1))
  RUNS=$((RUNS - 1))
done

AVERAGE_TIME=$((SUM / TOTAL))

echo -e "${GREEN}Average runtime after ${TIMES_RAN} runs: ${AVERAGE_TIME} ms"

if [[ "$EXTENSION" == "java" ]]; then
  echo -e "${GREEN}Removing class file..."
  rm *.class
elif [[ "$EXTENSION" == "cpp" ]]; then
  echo -e "${GREEN}Removing executable file..."
  rm a.out
else
  echo -e "${GREEN}No executable to remove for Python, exiting..."
fi

echo -e "${GREEN}Done"
